### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'product'

### ISSUE THREAD

**Issue by rhiannataub** [physicsranger/make4FGLxml#66] opened 2024-07-01 13:53 UTC
AttributeError: module 'numpy' has no attribute 'product'
I tried running the Fermi binned likelihood tutorial and ran into a little trouble on step 5. I'm working on a new laptop and recently got Anaconda installed, and when trying to run the code for step 5 I got the above error message. To fix it I had to 
pip install numpy==1.23.4
which uninstalled numpy 2.0 and I had to install the Galactic interstellar emission model https://fermi.gsfc.nasa.gov/ssc/data/access/lat/BackgroundModels.html and then the code worked. 
Just wanted to put it out there in case anyone else ran into this.

**Comment by physicsranger** [comment] 2024-07-03 12:09
Thank you for bringing this to my attention and for sharing a fix/work around.  I will make some time to dig around to figure out if I need to tweak the code and/or update the dependency versions.

**Comment by physicsranger** [comment] 2024-08-17 16:02
Sorry it has taken me so long to look into this.  It appears that product was deprecated as of numpy version 1.25.0 and was slated to be removed with numpy 2.0.  The code does not call numpy.product directly, but Pandas might.  I know this is somewhat long after the fact, but do you happen to know what version of Pandas you had installed?

When playing around with virtual environments, if I had numpy >= 2.0 installed and I installed pandas 2.2.0, it automatically downgraded my numpy.  This did not happen for pandas 2.2.2, and looking at the release notes for this version: "Pandas 2.2.2 is the first version of pandas that is generally compatible with the upcoming numpy 2.0 release"

Pandas 2.2.2 was out in April, and the TOML file for LATSourceModel does not restrict any version numbers, so I'm not sure why in July you didn't get a compatible version.

I think this is the root cause but 1) I'll wait to see if you can confirm the Pandas version and 2) I need to first figure out if there is a good way to handle this with the TOML file.

**Comment by leoScienceanalytics** [comment] 2024-10-07 18:12
I tried to debug quantitative finance code with quantstats (library) and this error appeared again, how to solve this? 
I tried this solution, but do not solver my problem

**Comment by physicsranger** [comment] 2024-11-10 17:22
I'm going to close this issue for now.  As far as I can tell, I can't condition library versions on each other, only on python version.  I think the fermitools are working on moving to a later version of NumPy which will likely make it feasible to use the latest Pandas.  For now, just make sure to install pandas <= 2.2.0 within the fermitools conda env and I think you'll be ok.

**Closed by physicsranger** 2024-11-10 17:22 UTC
